###1: create person
POST http://localhost:8084/api/v1/person/create
Content-Type: application/json

{
  "email": "john.cena@gmail.com",
  "lastName": "Ivanovich",
  "name": "John",
  "phone": "222-444",
  "surname": "Cena"
}

###2: get by id
GET http://localhost:8084/api/v1/person/76
Content-Type: application/json
